package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asignado generated by hbm2java
 */
public class Asignado  implements java.io.Serializable {


     private String chrAsigcodigo;
     private Empleado empleado;
     private Sucursal sucursal;
     private Date dttAsigfechaalta;
     private Date dttAsigfechabaja;

    public Asignado() {
    }

	
    public Asignado(String chrAsigcodigo, Empleado empleado, Sucursal sucursal, Date dttAsigfechaalta) {
        this.chrAsigcodigo = chrAsigcodigo;
        this.empleado = empleado;
        this.sucursal = sucursal;
        this.dttAsigfechaalta = dttAsigfechaalta;
    }
    public Asignado(String chrAsigcodigo, Empleado empleado, Sucursal sucursal, Date dttAsigfechaalta, Date dttAsigfechabaja) {
       this.chrAsigcodigo = chrAsigcodigo;
       this.empleado = empleado;
       this.sucursal = sucursal;
       this.dttAsigfechaalta = dttAsigfechaalta;
       this.dttAsigfechabaja = dttAsigfechabaja;
    }
   
    public String getChrAsigcodigo() {
        return this.chrAsigcodigo;
    }
    
    public void setChrAsigcodigo(String chrAsigcodigo) {
        this.chrAsigcodigo = chrAsigcodigo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Date getDttAsigfechaalta() {
        return this.dttAsigfechaalta;
    }
    
    public void setDttAsigfechaalta(Date dttAsigfechaalta) {
        this.dttAsigfechaalta = dttAsigfechaalta;
    }
    public Date getDttAsigfechabaja() {
        return this.dttAsigfechabaja;
    }
    
    public void setDttAsigfechabaja(Date dttAsigfechabaja) {
        this.dttAsigfechabaja = dttAsigfechabaja;
    }




}


