package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String chrCliecodigo;
     private String vchCliepaterno;
     private String vchCliematerno;
     private String vchClienombre;
     private String chrCliedni;
     private String vchClieciudad;
     private String vchCliedireccion;
     private String vchClietelefono;
     private String vchClieemail;
     private Set cuentas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String chrCliecodigo, String vchCliepaterno, String vchCliematerno, String vchClienombre, String chrCliedni, String vchClieciudad, String vchCliedireccion) {
        this.chrCliecodigo = chrCliecodigo;
        this.vchCliepaterno = vchCliepaterno;
        this.vchCliematerno = vchCliematerno;
        this.vchClienombre = vchClienombre;
        this.chrCliedni = chrCliedni;
        this.vchClieciudad = vchClieciudad;
        this.vchCliedireccion = vchCliedireccion;
    }
    public Cliente(String chrCliecodigo, String vchCliepaterno, String vchCliematerno, String vchClienombre, String chrCliedni, String vchClieciudad, String vchCliedireccion, String vchClietelefono, String vchClieemail, Set cuentas) {
       this.chrCliecodigo = chrCliecodigo;
       this.vchCliepaterno = vchCliepaterno;
       this.vchCliematerno = vchCliematerno;
       this.vchClienombre = vchClienombre;
       this.chrCliedni = chrCliedni;
       this.vchClieciudad = vchClieciudad;
       this.vchCliedireccion = vchCliedireccion;
       this.vchClietelefono = vchClietelefono;
       this.vchClieemail = vchClieemail;
       this.cuentas = cuentas;
    }
   
    public String getChrCliecodigo() {
        return this.chrCliecodigo;
    }
    
    public void setChrCliecodigo(String chrCliecodigo) {
        this.chrCliecodigo = chrCliecodigo;
    }
    public String getVchCliepaterno() {
        return this.vchCliepaterno;
    }
    
    public void setVchCliepaterno(String vchCliepaterno) {
        this.vchCliepaterno = vchCliepaterno;
    }
    public String getVchCliematerno() {
        return this.vchCliematerno;
    }
    
    public void setVchCliematerno(String vchCliematerno) {
        this.vchCliematerno = vchCliematerno;
    }
    public String getVchClienombre() {
        return this.vchClienombre;
    }
    
    public void setVchClienombre(String vchClienombre) {
        this.vchClienombre = vchClienombre;
    }
    public String getChrCliedni() {
        return this.chrCliedni;
    }
    
    public void setChrCliedni(String chrCliedni) {
        this.chrCliedni = chrCliedni;
    }
    public String getVchClieciudad() {
        return this.vchClieciudad;
    }
    
    public void setVchClieciudad(String vchClieciudad) {
        this.vchClieciudad = vchClieciudad;
    }
    public String getVchCliedireccion() {
        return this.vchCliedireccion;
    }
    
    public void setVchCliedireccion(String vchCliedireccion) {
        this.vchCliedireccion = vchCliedireccion;
    }
    public String getVchClietelefono() {
        return this.vchClietelefono;
    }
    
    public void setVchClietelefono(String vchClietelefono) {
        this.vchClietelefono = vchClietelefono;
    }
    public String getVchClieemail() {
        return this.vchClieemail;
    }
    
    public void setVchClieemail(String vchClieemail) {
        this.vchClieemail = vchClieemail;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


