package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1



/**
 * Contador generated by hbm2java
 */
public class Contador  implements java.io.Serializable {


     private String vchConttabla;
     private int intContitem;
     private int intContlongitud;

    public Contador() {
    }

    public Contador(String vchConttabla, int intContitem, int intContlongitud) {
       this.vchConttabla = vchConttabla;
       this.intContitem = intContitem;
       this.intContlongitud = intContlongitud;
    }
   
    public String getVchConttabla() {
        return this.vchConttabla;
    }
    
    public void setVchConttabla(String vchConttabla) {
        this.vchConttabla = vchConttabla;
    }
    public int getIntContitem() {
        return this.intContitem;
    }
    
    public void setIntContitem(int intContitem) {
        this.intContitem = intContitem;
    }
    public int getIntContlongitud() {
        return this.intContlongitud;
    }
    
    public void setIntContlongitud(int intContlongitud) {
        this.intContlongitud = intContlongitud;
    }




}


