package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Costomovimiento generated by hbm2java
 */
public class Costomovimiento  implements java.io.Serializable {


     private String chrMonecodigo;
     private Moneda moneda;
     private BigDecimal decCostimporte;

    public Costomovimiento() {
    }

    public Costomovimiento(Moneda moneda, BigDecimal decCostimporte) {
       this.moneda = moneda;
       this.decCostimporte = decCostimporte;
    }
   
    public String getChrMonecodigo() {
        return this.chrMonecodigo;
    }
    
    public void setChrMonecodigo(String chrMonecodigo) {
        this.chrMonecodigo = chrMonecodigo;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public BigDecimal getDecCostimporte() {
        return this.decCostimporte;
    }
    
    public void setDecCostimporte(BigDecimal decCostimporte) {
        this.decCostimporte = decCostimporte;
    }




}


