package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {


    private String chrCuencodigo;
    private Cliente cliente;
    private Empleado empleado;
    private Moneda moneda;
    private Sucursal sucursal;
    private double decCuensaldo;
    private Date dttCuenfechacreacion;
    private String vchCuenestado;
    private int intCuencontmov;
    private String chrCuenclave;
    private Set movimientos = new HashSet(0);

    public Cuenta() {
    }

    public Cuenta(String cuenta) {
        this.chrCuencodigo = cuenta;
    }

    public String getChrCuencodigo() {
        return this.chrCuencodigo;
    }

    public void setChrCuencodigo(String chrCuencodigo) {
        this.chrCuencodigo = chrCuencodigo;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public Moneda getMoneda() {
        return this.moneda;
    }

    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }

    public Sucursal getSucursal() {
        return this.sucursal;
    }

    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }

    public Double getDecCuensaldo() {
        return this.decCuensaldo;
    }

    public void setDecCuensaldo(double decCuensaldo) {
        this.decCuensaldo = decCuensaldo;
    }

    public Date getDttCuenfechacreacion() {
        return this.dttCuenfechacreacion;
    }

    public void setDttCuenfechacreacion(Date dttCuenfechacreacion) {
        this.dttCuenfechacreacion = dttCuenfechacreacion;
    }

    public String getVchCuenestado() {
        return this.vchCuenestado;
    }

    public void setVchCuenestado(String vchCuenestado) {
        this.vchCuenestado = vchCuenestado;
    }

    public int getIntCuencontmov() {
        return this.intCuencontmov;
    }

    public void setIntCuencontmov(int intCuencontmov) {
        this.intCuencontmov = intCuencontmov;
    }

    public String getChrCuenclave() {
        return this.chrCuenclave;
    }

    public void setChrCuenclave(String chrCuenclave) {
        this.chrCuenclave = chrCuenclave;
    }

    public Set getMovimientos() {
        return this.movimientos;
    }

    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }


}


