package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String chrEmplcodigo;
     private String vchEmplpaterno;
     private String vchEmplmaterno;
     private String vchEmplnombre;
     private String vchEmplciudad;
     private String vchEmpldireccion;
     private String vchEmplusuario;
     private String vchEmplclave;
     private Set movimientos = new HashSet(0);
     private Set asignados = new HashSet(0);
     private Set cuentas = new HashSet(0);

    public Empleado() {
    }

    public Empleado(String codigo) {
        this.chrEmplcodigo=codigo;

    }

    public String getChrEmplcodigo() {
        return this.chrEmplcodigo;
    }
    
    public void setChrEmplcodigo(String chrEmplcodigo) {
        this.chrEmplcodigo = chrEmplcodigo;
    }
    public String getVchEmplpaterno() {
        return this.vchEmplpaterno;
    }
    
    public void setVchEmplpaterno(String vchEmplpaterno) {
        this.vchEmplpaterno = vchEmplpaterno;
    }
    public String getVchEmplmaterno() {
        return this.vchEmplmaterno;
    }
    
    public void setVchEmplmaterno(String vchEmplmaterno) {
        this.vchEmplmaterno = vchEmplmaterno;
    }
    public String getVchEmplnombre() {
        return this.vchEmplnombre;
    }
    
    public void setVchEmplnombre(String vchEmplnombre) {
        this.vchEmplnombre = vchEmplnombre;
    }
    public String getVchEmplciudad() {
        return this.vchEmplciudad;
    }
    
    public void setVchEmplciudad(String vchEmplciudad) {
        this.vchEmplciudad = vchEmplciudad;
    }
    public String getVchEmpldireccion() {
        return this.vchEmpldireccion;
    }
    
    public void setVchEmpldireccion(String vchEmpldireccion) {
        this.vchEmpldireccion = vchEmpldireccion;
    }
    public String getVchEmplusuario() {
        return this.vchEmplusuario;
    }
    
    public void setVchEmplusuario(String vchEmplusuario) {
        this.vchEmplusuario = vchEmplusuario;
    }
    public String getVchEmplclave() {
        return this.vchEmplclave;
    }
    
    public void setVchEmplclave(String vchEmplclave) {
        this.vchEmplclave = vchEmplclave;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }
    public Set getAsignados() {
        return this.asignados;
    }
    
    public void setAsignados(Set asignados) {
        this.asignados = asignados;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


