package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Interesmensual generated by hbm2java
 */
public class Interesmensual  implements java.io.Serializable {


     private String chrMonecodigo;
     private Moneda moneda;
     private BigDecimal decInteimporte;

    public Interesmensual() {
    }

    public Interesmensual(Moneda moneda, BigDecimal decInteimporte) {
       this.moneda = moneda;
       this.decInteimporte = decInteimporte;
    }
   
    public String getChrMonecodigo() {
        return this.chrMonecodigo;
    }
    
    public void setChrMonecodigo(String chrMonecodigo) {
        this.chrMonecodigo = chrMonecodigo;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public BigDecimal getDecInteimporte() {
        return this.decInteimporte;
    }
    
    public void setDecInteimporte(BigDecimal decInteimporte) {
        this.decInteimporte = decInteimporte;
    }




}


