package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda  implements java.io.Serializable {


     private String chrMonecodigo;
     private String vchMonedescripcion;
     private Interesmensual interesmensual;
     private Set cuentas = new HashSet(0);
     private Costomovimiento costomovimiento;
     private Cargomantenimiento cargomantenimiento;

    public Moneda() {
    }

	
    public Moneda(String chrMonecodigo, String vchMonedescripcion) {
        this.chrMonecodigo = chrMonecodigo;
        this.vchMonedescripcion = vchMonedescripcion;
    }
    public Moneda(String chrMonecodigo, String vchMonedescripcion, Interesmensual interesmensual, Set cuentas, Costomovimiento costomovimiento, Cargomantenimiento cargomantenimiento) {
       this.chrMonecodigo = chrMonecodigo;
       this.vchMonedescripcion = vchMonedescripcion;
       this.interesmensual = interesmensual;
       this.cuentas = cuentas;
       this.costomovimiento = costomovimiento;
       this.cargomantenimiento = cargomantenimiento;
    }
   
    public String getChrMonecodigo() {
        return this.chrMonecodigo;
    }
    
    public void setChrMonecodigo(String chrMonecodigo) {
        this.chrMonecodigo = chrMonecodigo;
    }
    public String getVchMonedescripcion() {
        return this.vchMonedescripcion;
    }
    
    public void setVchMonedescripcion(String vchMonedescripcion) {
        this.vchMonedescripcion = vchMonedescripcion;
    }
    public Interesmensual getInteresmensual() {
        return this.interesmensual;
    }
    
    public void setInteresmensual(Interesmensual interesmensual) {
        this.interesmensual = interesmensual;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Costomovimiento getCostomovimiento() {
        return this.costomovimiento;
    }
    
    public void setCostomovimiento(Costomovimiento costomovimiento) {
        this.costomovimiento = costomovimiento;
    }
    public Cargomantenimiento getCargomantenimiento() {
        return this.cargomantenimiento;
    }
    
    public void setCargomantenimiento(Cargomantenimiento cargomantenimiento) {
        this.cargomantenimiento = cargomantenimiento;
    }




}


