package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private String chrSucucodigo;
     private String vchSucunombre;
     private String vchSucuciudad;
     private String vchSucudireccion;
     private int intSucucontcuenta;
     private Set cuentas = new HashSet(0);
     private Set asignados = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(String chrSucucodigo, String vchSucunombre, String vchSucuciudad, int intSucucontcuenta) {
        this.chrSucucodigo = chrSucucodigo;
        this.vchSucunombre = vchSucunombre;
        this.vchSucuciudad = vchSucuciudad;
        this.intSucucontcuenta = intSucucontcuenta;
    }
    public Sucursal(String chrSucucodigo, String vchSucunombre, String vchSucuciudad, String vchSucudireccion, int intSucucontcuenta, Set cuentas, Set asignados) {
       this.chrSucucodigo = chrSucucodigo;
       this.vchSucunombre = vchSucunombre;
       this.vchSucuciudad = vchSucuciudad;
       this.vchSucudireccion = vchSucudireccion;
       this.intSucucontcuenta = intSucucontcuenta;
       this.cuentas = cuentas;
       this.asignados = asignados;
    }
   
    public String getChrSucucodigo() {
        return this.chrSucucodigo;
    }
    
    public void setChrSucucodigo(String chrSucucodigo) {
        this.chrSucucodigo = chrSucucodigo;
    }
    public String getVchSucunombre() {
        return this.vchSucunombre;
    }
    
    public void setVchSucunombre(String vchSucunombre) {
        this.vchSucunombre = vchSucunombre;
    }
    public String getVchSucuciudad() {
        return this.vchSucuciudad;
    }
    
    public void setVchSucuciudad(String vchSucuciudad) {
        this.vchSucuciudad = vchSucuciudad;
    }
    public String getVchSucudireccion() {
        return this.vchSucudireccion;
    }
    
    public void setVchSucudireccion(String vchSucudireccion) {
        this.vchSucudireccion = vchSucudireccion;
    }
    public int getIntSucucontcuenta() {
        return this.intSucucontcuenta;
    }
    
    public void setIntSucucontcuenta(int intSucucontcuenta) {
        this.intSucucontcuenta = intSucucontcuenta;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getAsignados() {
        return this.asignados;
    }
    
    public void setAsignados(Set asignados) {
        this.asignados = asignados;
    }




}


