package com.example.guevaracabrera.cuentabancario.Entidaes;
// Generated 10-nov-2015 17:47:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipomovimiento generated by hbm2java
 */
public class Tipomovimiento  implements java.io.Serializable {


     private String chrTipocodigo;
     private String vchTipodescripcion;
     private String vchTipoaccion;
     private String vchTipoestado;
     private Set movimientos = new HashSet(0);

    public Tipomovimiento() {
    }

    public Tipomovimiento(String chrTipocodigo, String vchTipodescripcion, String vchTipoaccion) {
        this.chrTipocodigo = chrTipocodigo;
        this.vchTipodescripcion = vchTipodescripcion;
        this.vchTipoaccion = vchTipoaccion;
    }

    public String getChrTipocodigo() {
        return this.chrTipocodigo;
    }
    
    public void setChrTipocodigo(String chrTipocodigo) {
        this.chrTipocodigo = chrTipocodigo;
    }
    public String getVchTipodescripcion() {
        return this.vchTipodescripcion;
    }
    
    public void setVchTipodescripcion(String vchTipodescripcion) {
        this.vchTipodescripcion = vchTipodescripcion;
    }
    public String getVchTipoaccion() {
        return this.vchTipoaccion;
    }
    
    public void setVchTipoaccion(String vchTipoaccion) {
        this.vchTipoaccion = vchTipoaccion;
    }
    public String getVchTipoestado() {
        return this.vchTipoestado;
    }
    
    public void setVchTipoestado(String vchTipoestado) {
        this.vchTipoestado = vchTipoestado;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


