package com.example.guevaracabrera.productosventas.Modelo;
// Generated 21-nov-2015 23:17:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idcat;
     private String nombre;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idcat, String nombre) {
        this.idcat = idcat;
        this.nombre = nombre;
    }
    public Categoria(int idcat, String nombre, Set productos) {
       this.idcat = idcat;
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public int getIdcat() {
        return this.idcat;
    }
    
    public void setIdcat(int idcat) {
        this.idcat = idcat;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


