package com.example.guevaracabrera.productosventas.Modelo;
// Generated 21-nov-2015 23:17:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private Categoria idcat;
    private Integer idprod;
    private String nombre;
    private Double precio;
    private int stock;

    public Producto() {
    }

    public Producto(Categoria categoria, String nombre, Double precio, int stock) {
        this.idcat = categoria;
        this.nombre = nombre;
        this.precio = precio;
        this.stock = stock;
    }

    public Integer getIdprod() {
        return idprod;
    }

    public void setIdprod(Integer idprod) {
        this.idprod = idprod;
    }

    public Categoria getIdcat() {
        return idcat;
    }

    public void setIdcat(Categoria idcat) {
        this.idcat = idcat;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getPrecio() {
        return precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }
}


